title: <p align = 'centre' /p> Pravin koli
logo: /assets/img/logo.png
description: The data Science lerner from UpGrad Platform with IIITB.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
